version: '3'

services:
  php:
    container_name: php-symfony
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www

  nginx:
    container_name: nginx-symfony
    image: nginx:1.21.5-alpine
    ports:
      - '8099:80'
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      
