version: '3'

services:
  php:
    container_name: php-symfony
    build:
      dockerfile: .docker/php/Dockerfile
      context: .
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www

  nginx:
    container_name: nginx-symfony
    image: nginx:1.21.5-alpine
    ports:
      - '8099:80'
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
    ports:
      - "8082:80"